name: admin-ui-line
namespace: official
version: 0.0.1-1
author: Wazo Team
display_name: Lines
min_wazo_version: 18.01
tags:
  - beta
  - line
homepage: https://github.com/wazo-pbx/wazo-admin-ui-line
depends:
  - name: admin-ui-context
    namespace: official
    version: 1.0.1-1
  - name: admin-ui-extension
    namespace: official
    version: 1.2.0-1
