name: admin-ui-line
namespace: official
version: 1.0.0-3
author: Wazo Team
display_name: Lines
min_wazo_version: 18.02
tags:
  - line
homepage: https://github.com/wazo-pbx/wazo-admin-ui-line
icon: exchange
depends:
  - name: admin-ui-context
    namespace: official
  - name: admin-ui-extension
    namespace: official
