plugin_format_version: 2
name: admin-ui-line
namespace: official
version: 1.0.0-1
author: Wazo Team
display_name: Lines
min_wazo_version: 18.02
tags:
  - line
homepage: https://github.com/wazo-pbx/wazo-admin-ui-line
depends:
  - name: admin-ui-context
    namespace: official
    version: ">= 1.1.1-2"
  - name: admin-ui-extension
    namespace: official
    version: ">= 1.2.0-2"
